version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ragaiq-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ragaiq
      POSTGRES_PASSWORD: ragaiq_dev_2024
      POSTGRES_DB: ragaiq_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: