# docker-compose.dev.yml
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ragaiq-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ragaiq
      POSTGRES_PASSWORD: ragaiq_dev_2024
      POSTGRES_DB: ragaiq_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ragaiq -d ragaiq_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ragaiq-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ragaiq.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: ragaiq-network